---
format_version: '13'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: flutter

# Environment variables
app:
  envs:
  - FLUTTER_VERSION: "3.24.0"
  - SHARD_COUNT: "3"  # Fixed number of shards (always split tests across 3 shards)

# Workflows
workflows:

  # Main coordinator workflow - calculates shards and shares configuration
  shard_coordinator:
    description: Analyzes changed packages and calculates dynamic shards
    steps:
    - git-clone@8: {}

    - flutter-installer@1:
        inputs:
        - version: $FLUTTER_VERSION
        - is_update: "false"

    - script@1:
        title: Install Melos
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            flutter pub global activate melos
            export PATH="$PATH:$HOME/.pub-cache/bin"

    - script@1:
        title: Bootstrap packages
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            export PATH="$PATH:$HOME/.pub-cache/bin"
            melos bootstrap

    - script@1:
        title: Calculate test shards and create array
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            echo "Calculating shards based on changed files..."
            echo "Fixed shard count: $SHARD_COUNT"

            # Get changed files
            CHANGED_FILES=$(git diff --name-only HEAD 2>/dev/null || echo "")
            if [ -z "$CHANGED_FILES" ]; then
              CHANGED_FILES_JSON="[]"
            else
              CHANGED_FILES_JSON=$(echo "$CHANGED_FILES" | jq -R -s -c 'split("\n") | map(select(length > 0))')
            fi

            # Analyze to get affected packages
            ANALYSIS=$(dart .ci/scripts/shard_calculator.dart analyze "$CHANGED_FILES_JSON")
            ALL_PACKAGES=$(echo "$ANALYSIS" | jq -r '.all | join(",")')
            MODIFIED_PACKAGES=$(echo "$ANALYSIS" | jq -r '.modified | join(",")')

            echo "All affected packages: $ALL_PACKAGES"
            echo "Modified packages: $MODIFIED_PACKAGES"

            # Shard the packages using fixed SHARD_COUNT
            # Capture output to both send to envman AND build SHARD_ARRAY
            SHARD_OUTPUT=$(dart .ci/scripts/shard_calculator.dart shard "$ALL_PACKAGES" $SHARD_COUNT)

            # Send all shard variables to envman and collect for array
            SHARD_VALUES=()
            while IFS='=' read -r key value; do
              echo "$key=$value"

              # Store SHARD_X_PACKAGES values in array for SHARD_ARRAY
              if [[ "$key" == SHARD_*_PACKAGES ]]; then
                SHARD_VALUES+=("$value")
              fi

              envman add --key "$key" --value "$value"
            done <<< "$SHARD_OUTPUT"

            envman add --key MODIFIED_PACKAGES --value "$MODIFIED_PACKAGES"

            # Display shard configuration
            echo "===================="
            echo "Shard Configuration:"
            echo "===================="
            echo "Shard Count: $SHARD_COUNT"

            # Create JSON array of shard assignments from captured values
            # Format: ["feature_a,feature_b", "feature_c,feature_d", ...]
            SHARD_ARRAY="["
            for i in "${!SHARD_VALUES[@]}"; do
              packages="${SHARD_VALUES[$i]}"

              if [ $i -gt 0 ]; then
                SHARD_ARRAY="${SHARD_ARRAY},"
              fi
              SHARD_ARRAY="${SHARD_ARRAY}\"${packages}\""

              echo "Shard $i: $packages"
            done
            SHARD_ARRAY="${SHARD_ARRAY}]"

            echo "Shard Array: $SHARD_ARRAY"
            echo "Modified Packages: $MODIFIED_PACKAGES"
            echo "===================="

            envman add --key SHARD_ARRAY --value "$SHARD_ARRAY"

    # Share pipeline variables using newline-separated format
    - share-pipeline-variable@1:
        title: Share pipeline variables
        inputs:
        - variables: |-
            SHARD_ARRAY
            MODIFIED_PACKAGES

  # Fixed shard worker - runs N times in parallel (where N = SHARD_COUNT)
  # Each parallel instance automatically gets $BITRISE_IO_PARALLEL_INDEX (0, 1, 2, ..., N-1)
  # Packages are distributed across all shards, some shards may be empty
  test_shard:
    description: Run tests for assigned shard packages
    steps:
    - git-clone@8: {}

    - flutter-installer@1:
        inputs:
        - version: $FLUTTER_VERSION

    - script@1:
        title: Install Melos
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            flutter pub global activate melos
            export PATH="$PATH:$HOME/.pub-cache/bin"

    - script@1:
        title: Bootstrap packages
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            export PATH="$PATH:$HOME/.pub-cache/bin"
            melos bootstrap

    - script@1:
        title: Extract packages for this shard from array
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            echo "========================================="
            echo "Shard Index: $BITRISE_IO_PARALLEL_INDEX"
            echo "Shard Count: $SHARD_COUNT"
            echo "Shard Array: $SHARD_ARRAY"
            echo "========================================="

            # Parse JSON array and extract packages for this shard index
            # SHARD_ARRAY is like: ["feature_a,feature_b", "feature_c,feature_d"]
            # We want to get the element at index $BITRISE_IO_PARALLEL_INDEX

            # Use jq to parse JSON array (jq is pre-installed on Bitrise stacks)
            PACKAGES=$(echo "$SHARD_ARRAY" | jq -r ".[$BITRISE_IO_PARALLEL_INDEX]")

            if [ -z "$PACKAGES" ] || [ "$PACKAGES" = "null" ]; then
              echo "ERROR: No packages found for shard $BITRISE_IO_PARALLEL_INDEX"
              exit 1
            fi

            echo "Packages for shard $BITRISE_IO_PARALLEL_INDEX: $PACKAGES"
            envman add --key SHARD_PACKAGES --value "$PACKAGES"

    - script@1:
        title: Install test report tool
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            # Install junitreport for converting Flutter JSON to JUnit XML
            flutter pub global activate junitreport

    - script@1:
        title: Run tests for assigned packages
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            export PATH="$PATH:$HOME/.pub-cache/bin"

            echo "========================================="
            echo "Testing Shard $BITRISE_IO_PARALLEL_INDEX"
            echo "Mode: Fixed sharding ($SHARD_COUNT shards in parallel)"
            echo "Packages: $SHARD_PACKAGES"
            echo "========================================="

            IFS=',' read -ra PKG_ARRAY <<< "$SHARD_PACKAGES"

            # Create directories for test results
            mkdir -p test-results
            mkdir -p "$BITRISE_TEST_RESULT_DIR"

            FAILED=0

            for package in "${PKG_ARRAY[@]}"; do
              echo ""
              echo "========================================="
              echo "Testing package: $package"
              echo "========================================="

              cd "packages/$package"

              # Run tests and generate JUnit XML directly
              # Flutter can output to file-reporter for JUnit format
              JUNIT_OUTPUT="$BITRISE_TEST_RESULT_DIR/shard${BITRISE_IO_PARALLEL_INDEX}_${package}.xml"

              if flutter test --reporter=expanded --file-reporter="json:test-output.json" 2>&1; then
                echo "✅ $package tests passed"
              else
                echo "❌ $package tests failed"
                FAILED=1
              fi

              # Convert test-output.json to JUnit XML using junitreport
              if [ -f "test-output.json" ]; then
                tojunit --input test-output.json --output "$JUNIT_OUTPUT" || {
                  # Fallback: create basic JUnit XML if conversion fails
                  echo "Warning: junitreport conversion failed, creating basic report"
                  cat << EOF > "$JUNIT_OUTPUT"
            <?xml version="1.0" encoding="UTF-8"?>
            <testsuites name="$package">
              <testsuite name="$package" tests="1">
                <testcase name="Tests" classname="$package">
                </testcase>
              </testsuite>
            </testsuites>
            EOF
                }
                echo "Generated JUnit report: $JUNIT_OUTPUT"
              else
                echo "Warning: No test output found for $package"
              fi

              cd ../..
            done

            echo ""
            echo "========================================="
            echo "Test Results Summary"
            echo "========================================="
            echo "Shard: $BITRISE_IO_PARALLEL_INDEX"
            echo "Packages tested: ${#PKG_ARRAY[@]}"
            echo "JUnit reports generated in: $BITRISE_TEST_RESULT_DIR"
            ls -la "$BITRISE_TEST_RESULT_DIR" || echo "No reports generated"
            echo "========================================="

            if [ $FAILED -eq 1 ]; then
              echo ""
              echo "❌ Shard $BITRISE_IO_PARALLEL_INDEX: Some tests failed!"
              exit 1
            fi

            echo ""
            echo "✅ Shard $BITRISE_IO_PARALLEL_INDEX: All tests passed!"

    - deploy-to-bitrise-io@2:
        title: Deploy test results
        inputs:
        - deploy_path: test-results/
        - is_compress: "true"
        - is_enable_public_page: "false"

  # Collect and aggregate results from all shards
  collect_results:
    description: Aggregate test results from all shards and generate final report
    steps:
    - script@1:
        title: Download artifacts from all shards
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            echo "========================================="
            echo "Collecting Test Results"
            echo "Shard Count: $SHARD_COUNT"
            echo "========================================="

            # Pull artifacts from previous stage
            # Note: Bitrise automatically makes artifacts from dependent workflows available

            # Create aggregated results directory
            mkdir -p aggregated-results

            echo "All shard artifacts are available in the build artifacts"

    - script@1:
        title: Generate combined test report
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            echo "========================================="
            echo "Test Summary"
            echo "========================================="
            echo "Total Shards: $SHARD_COUNT"
            echo "Modified Packages: $MODIFIED_PACKAGES"
            echo ""

            # Count total test results (if available)
            if [ -d "test-results" ]; then
              TOTAL_FILES=$(find test-results -name "*.json" | wc -l)
              echo "Test result files: $TOTAL_FILES"
            fi

            echo ""
            echo "✅ All shard tests completed successfully!"
            echo "========================================="

            # Here you could add:
            # - JUnit XML merging
            # - Coverage report aggregation
            # - Test result parsing and summary
            # - Slack/email notifications

    - script@1:
        title: Post summary to GitHub (optional)
        inputs:
        - content: |-
            #!/bin/bash
            set -e

            # Example: Post comment to PR with test results
            # Requires GitHub token and PR number

            if [ -n "$GITHUB_TOKEN" ] && [ -n "$PULL_REQUEST_ID" ]; then
              echo "Posting results to GitHub PR #$PULL_REQUEST_ID"

              # Create summary
              SUMMARY="### 🧪 Test Results

              - **Shards**: $SHARD_COUNT
              - **Modified packages**: $MODIFIED_PACKAGES
              - **Status**: ✅ All tests passed

              [View detailed results]($BITRISE_BUILD_URL)"

              # Post comment (example - adjust for your setup)
              # gh pr comment $PULL_REQUEST_ID --body "$SUMMARY"

              echo "GitHub notification skipped (configure GITHUB_TOKEN)"
            else
              echo "GitHub notification skipped (GITHUB_TOKEN not set)"
            fi
        is_always_run: false

# Graph-based Pipeline with Fixed Parallelism
pipelines:
  flutter_test_pipeline:
    workflows:
      # Step 1: Analyze packages and distribute across fixed shards
      shard_coordinator:
        depends_on: []

      # Step 2: Run tests in parallel across fixed number of shards
      # SHARD_COUNT is fixed (e.g., 5), packages are distributed evenly
      # Empty shards will run but complete quickly with no tests
      test_shard:
        depends_on:
        - shard_coordinator
        parallel: $SHARD_COUNT  # Fixed parallelism (e.g., 5 shards)

      # Step 3: Collect results after all shards complete
      collect_results:
        depends_on:
        - test_shard  # Waits for ALL copies to complete

# Default meta configuration
meta:
  bitrise.io:
    stack: linux-docker-android-22.04
    machine_type_id: standard
