---
format_version: '13'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: flutter

# Environment variables
app:
  envs:
  - FLUTTER_VERSION: "3.24.0"
  - PACKAGES_PER_SHARD: "2"  # Number of packages per shard (calculates dynamic shard count)
  #- SHARD_COUNT: "1"  # Will be set by shard_calculator when triggering test_pipeline
  #- BITRISE_API_TOKEN: ""  # Set this as a Secret in Bitrise Workflow Editor

# Workflows
workflows:

  # Main coordinator workflow - calculates shards and shares configuration
  shard_coordinator:
    description: Analyzes changed packages and calculates dynamic shards
    steps:
    - git-clone@8: {}

    - flutter-installer@1:
        inputs:
        - version: $FLUTTER_VERSION
        - is_update: "false"

    - script@1:
        title: Install Melos
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            flutter pub global activate melos
            export PATH="$PATH:$HOME/.pub-cache/bin"

    - script@1:
        title: Bootstrap packages
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            export PATH="$PATH:$HOME/.pub-cache/bin"
            melos bootstrap

    - script@1:
        title: Calculate dynamic shards and trigger test pipeline
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            echo "Calculating dynamic shards based on changed files..."
            echo "Packages per shard: $PACKAGES_PER_SHARD"

            # Get changed files
            CHANGED_FILES=$(git diff --name-only HEAD 2>/dev/null || echo "")
            if [ -z "$CHANGED_FILES" ]; then
              CHANGED_FILES_JSON="[]"
            else
              CHANGED_FILES_JSON=$(echo "$CHANGED_FILES" | jq -R -s -c 'split("\n") | map(select(length > 0))')
            fi

            # Analyze to get affected packages
            ANALYSIS=$(dart .ci/scripts/shard_calculator.dart analyze "$CHANGED_FILES_JSON")
            ALL_PACKAGES=$(echo "$ANALYSIS" | jq -r '.all | join(",")')
            MODIFIED_PACKAGES=$(echo "$ANALYSIS" | jq -r '.modified | join(",")')

            echo "All affected packages: $ALL_PACKAGES"
            echo "Modified packages: $MODIFIED_PACKAGES"

            # Count packages for display
            PACKAGE_COUNT=$(echo "$ALL_PACKAGES" | tr ',' '\n' | grep -v '^$' | wc -l | tr -d ' ')
            echo "Package count: $PACKAGE_COUNT"

            # Shard the packages using PACKAGES_PER_SHARD (dart script calculates shard count)
            # Capture output to both send to envman AND build SHARD_ARRAY
            SHARD_OUTPUT=$(dart .ci/scripts/shard_calculator.dart shard "$ALL_PACKAGES" $PACKAGES_PER_SHARD)

            # Send all shard variables to envman and collect for array
            SHARD_VALUES=()
            CALCULATED_SHARD_COUNT=0
            while IFS='=' read -r key value; do
              echo "$key=$value"

              # Store SHARD_X_PACKAGES values in array for SHARD_ARRAY
              if [[ "$key" == SHARD_*_PACKAGES ]]; then
                SHARD_VALUES+=("$value")
              fi

              # Capture SHARD_COUNT
              if [[ "$key" == "SHARD_COUNT" ]]; then
                CALCULATED_SHARD_COUNT=$value
              fi

              envman add --key "$key" --value "$value"
            done <<< "$SHARD_OUTPUT"

            envman add --key MODIFIED_PACKAGES --value "$MODIFIED_PACKAGES"

            # Display shard configuration
            echo "===================="
            echo "Shard Configuration:"
            echo "===================="
            echo "Shard Count: $CALCULATED_SHARD_COUNT"

            # Create JSON array of shard assignments from captured values
            # Format: ["feature_a,feature_b", "feature_c,feature_d", ...]
            SHARD_ARRAY="["
            for i in "${!SHARD_VALUES[@]}"; do
              packages="${SHARD_VALUES[$i]}"

              if [ $i -gt 0 ]; then
                SHARD_ARRAY="${SHARD_ARRAY},"
              fi
              SHARD_ARRAY="${SHARD_ARRAY}\"${packages}\""

              echo "Shard $i: $packages"
            done
            SHARD_ARRAY="${SHARD_ARRAY}]"

            echo "Shard Array: $SHARD_ARRAY"
            echo "Modified Packages: $MODIFIED_PACKAGES"
            echo "===================="

            envman add --key SHARD_ARRAY --value "$SHARD_ARRAY"

    - script@1:
        title: Trigger test_pipeline with calculated shard count
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            echo "Triggering test_pipeline with SHARD_COUNT=$SHARD_COUNT"

            # Check if BITRISE_API_TOKEN is set
            if [ -z "$BITRISE_API_TOKEN" ]; then
              echo "ERROR: BITRISE_API_TOKEN is not set!"
              echo "Please add it as a Secret in Bitrise Workflow Editor"
              exit 1
            fi

            # Escape quotes in SHARD_ARRAY for JSON embedding
            ESCAPED_SHARD_ARRAY=$(echo "$SHARD_ARRAY" | sed 's/"/\\"/g')

            # Trigger the test_pipeline via Bitrise Build Trigger API
            RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
              "https://api.bitrise.io/v0.1/apps/$BITRISE_APP_SLUG/builds" \
              -H "Authorization: token $BITRISE_API_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{
                \"hook_info\": {
                  \"type\": \"bitrise\"
                },
                \"build_params\": {
                  \"pipeline_id\": \"test_pipeline\",
                  \"branch\": \"$BITRISE_GIT_BRANCH\",
                  \"commit_hash\": \"$GIT_CLONE_COMMIT_HASH\",
                  \"commit_message\": \"Dynamic shard test run - $CALCULATED_SHARD_COUNT shards\",
                  \"environments\": [
                    {\"key\": \"SHARD_COUNT\", \"value\": \"$SHARD_COUNT\", \"is_expand\": false},
                    {\"key\": \"SHARD_ARRAY\", \"value\": \"$ESCAPED_SHARD_ARRAY\", \"is_expand\": false},
                    {\"key\": \"MODIFIED_PACKAGES\", \"value\": \"$MODIFIED_PACKAGES\", \"is_expand\": false}
                  ]
                }
              }")

            HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
            BODY=$(echo "$RESPONSE" | sed '$d')

            echo "HTTP Status: $HTTP_CODE"
            echo "Response: $BODY"

            if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
              BUILD_SLUG=$(echo "$BODY" | jq -r '.build_slug // empty')
              BUILD_URL=$(echo "$BODY" | jq -r '.build_url // empty')
              echo "✅ Test pipeline triggered successfully!"
              echo "Build Slug: $BUILD_SLUG"
              echo "Build URL: $BUILD_URL"
            else
              echo "❌ Failed to trigger test pipeline"
              exit 1
            fi

  # Dynamic shard worker - runs N times in parallel (where N = dynamically calculated SHARD_COUNT)
  # Each parallel instance automatically gets $BITRISE_IO_PARALLEL_INDEX (0, 1, 2, ..., N-1)
  # N is determined by: ceil(package_count / PACKAGES_PER_SHARD)
  test_shard:
    description: Run tests for assigned shard packages
    steps:
    - git-clone@8: {}

    - flutter-installer@1:
        inputs:
        - version: $FLUTTER_VERSION

    - script@1:
        title: Install Melos
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            flutter pub global activate melos
            export PATH="$PATH:$HOME/.pub-cache/bin"

    - script@1:
        title: Bootstrap packages
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            export PATH="$PATH:$HOME/.pub-cache/bin"
            melos bootstrap

    - script@1:
        title: Extract packages for this shard from array
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            echo "========================================="
            echo "Shard Index: $BITRISE_IO_PARALLEL_INDEX"
            echo "Shard Count: $SHARD_COUNT"
            echo "Shard Array: $SHARD_ARRAY"
            echo "========================================="

            # Parse JSON array and extract packages for this shard index
            # SHARD_ARRAY is like: ["feature_a,feature_b", "feature_c,feature_d"]
            # We want to get the element at index $BITRISE_IO_PARALLEL_INDEX

            # Use jq to parse JSON array (jq is pre-installed on Bitrise stacks)
            PACKAGES=$(echo "$SHARD_ARRAY" | jq -r ".[$BITRISE_IO_PARALLEL_INDEX]")

            if [ -z "$PACKAGES" ] || [ "$PACKAGES" = "null" ]; then
              echo "ERROR: No packages found for shard $BITRISE_IO_PARALLEL_INDEX"
              exit 1
            fi

            echo "Packages for shard $BITRISE_IO_PARALLEL_INDEX: $PACKAGES"
            envman add --key SHARD_PACKAGES --value "$PACKAGES"

    - script@1:
        title: Install test report tool
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            # Install junitreport for converting Flutter JSON to JUnit XML
            flutter pub global activate junitreport

    - script@1:
        title: Run tests for assigned packages
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            export PATH="$PATH:$HOME/.pub-cache/bin"

            echo "========================================="
            echo "Testing Shard $BITRISE_IO_PARALLEL_INDEX"
            echo "Mode: Fixed sharding ($SHARD_COUNT shards in parallel)"
            echo "Packages: $SHARD_PACKAGES"
            echo "========================================="

            IFS=',' read -ra PKG_ARRAY <<< "$SHARD_PACKAGES"

            # Create directories for test results
            mkdir -p test-results
            mkdir -p "$BITRISE_TEST_RESULT_DIR"

            FAILED=0

            for package in "${PKG_ARRAY[@]}"; do
              echo ""
              echo "========================================="
              echo "Testing package: $package"
              echo "========================================="

              cd "packages/$package"

              # Create subdirectory for this test run
              TEST_RUN_DIR="$BITRISE_TEST_RESULT_DIR/shard${BITRISE_IO_PARALLEL_INDEX}_${package}"
              mkdir -p "$TEST_RUN_DIR"

              JUNIT_OUTPUT="$TEST_RUN_DIR/junit.xml"

              if flutter test --reporter=expanded --file-reporter="json:test-output.json" 2>&1; then
                echo "✅ $package tests passed"
              else
                echo "❌ $package tests failed"
                FAILED=1
              fi

              # Convert test-output.json to JUnit XML using junitreport
              if [ -f "test-output.json" ]; then
                tojunit --input test-output.json --output "$JUNIT_OUTPUT" || {
                  # Fallback: create basic JUnit XML if conversion fails
                  echo "Warning: junitreport conversion failed, creating basic report"
                  cat << 'XMLEOF' > "$JUNIT_OUTPUT"
            <?xml version="1.0" encoding="UTF-8"?>
            <testsuites name="test">
              <testsuite name="test" tests="1">
                <testcase name="Tests" classname="test">
                </testcase>
              </testsuite>
            </testsuites>
            XMLEOF
                }
                echo "Generated JUnit report: $JUNIT_OUTPUT"
              else
                echo "Warning: No test output found for $package"
              fi

              # Create test-info.json with test name
              echo "{\"test-name\":\"Shard $BITRISE_IO_PARALLEL_INDEX - $package\"}" > "$TEST_RUN_DIR/test-info.json"
              echo "Generated test-info.json for $package"

              cd ../..
            done

            echo ""
            echo "========================================="
            echo "Test Results Summary"
            echo "========================================="
            echo "Shard: $BITRISE_IO_PARALLEL_INDEX"
            echo "Packages tested: ${#PKG_ARRAY[@]}"
            echo "JUnit reports generated in: $BITRISE_TEST_RESULT_DIR"
            ls -la "$BITRISE_TEST_RESULT_DIR" || echo "No reports generated"
            echo "========================================="

            if [ $FAILED -eq 1 ]; then
              echo ""
              echo "❌ Shard $BITRISE_IO_PARALLEL_INDEX: Some tests failed!"
              exit 1
            fi

            echo ""
            echo "✅ Shard $BITRISE_IO_PARALLEL_INDEX: All tests passed!"

# Pipelines
pipelines:
  # Main test pipeline - triggered by shard_calculator workflow via API
  # SHARD_COUNT is passed as environment variable from shard_calculator
  test_pipeline:
    workflows:
      # Run tests in parallel - SHARD_COUNT determines number of parallel instances
      # Each instance gets $BITRISE_IO_PARALLEL_INDEX (0, 1, 2, ..., SHARD_COUNT-1)
      test_shard:
        depends_on: []
        parallel: $SHARD_COUNT  # Dynamic parallelism set by shard_calculator


# Default meta configuration
meta:
  bitrise.io:
    stack: linux-docker-android-22.04
    machine_type_id: standard
