---
format_version: '13'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: flutter

# Environment variables
app:
  envs:
  - FLUTTER_VERSION: "3.24.0"
  - SHARD_THRESHOLD: "4"  # If packages <= threshold, run in single shard mode
  - PACKAGES_PER_SHARD: "2"  # Number of packages per shard (calculates dynamic shard count)

# Workflows
workflows:

  # Main coordinator workflow - calculates dynamic shards and shares configuration
  shard_coordinator:
    description: Analyzes changed packages, calculates dynamic shard count, and distributes packages across shards
    steps:
    - git-clone@8: {}

    - flutter-installer@1:
        inputs:
        - version: $FLUTTER_VERSION
        - is_update: "false"

    - script@1:
        title: Install Melos
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            flutter pub global activate melos
            export PATH="$PATH:$HOME/.pub-cache/bin"

    - script@1:
        title: Bootstrap packages
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            export PATH="$PATH:$HOME/.pub-cache/bin"
            melos bootstrap

    - script@1:
        title: Calculate dynamic shards and create array
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            echo "Calculating dynamic shards based on changed files..."
            echo "Shard threshold: $SHARD_THRESHOLD"
            echo "Packages per shard: $PACKAGES_PER_SHARD"

            # Run the shard calculator in auto mode
            # It will analyze changes, detect threshold, and create shards automatically
            SHARD_OUTPUT=$(dart .ci/scripts/shard_calculator.dart auto $SHARD_THRESHOLD $PACKAGES_PER_SHARD)

            # Send all shard variables to envman and collect for array
            SHARD_VALUES=()
            CALCULATED_SHARD_COUNT=0
            while IFS='=' read -r key value; do
              echo "$key=$value"

              # Store SHARD_X_PACKAGES values in array for SHARD_ARRAY
              if [[ "$key" == SHARD_*_PACKAGES ]]; then
                SHARD_VALUES+=("$value")
              fi

              # Capture SHARD_COUNT
              if [[ "$key" == "SHARD_COUNT" ]]; then
                CALCULATED_SHARD_COUNT=$value
              fi

              envman add --key "$key" --value "$value"
            done <<< "$SHARD_OUTPUT"

            # Display shard configuration
            echo "===================="
            echo "Shard Configuration:"
            echo "===================="
            echo "Shard Count: $CALCULATED_SHARD_COUNT"

            # Create JSON array of shard assignments from captured values
            # Format: ["feature_a,feature_b", "feature_c,feature_d", ...]
            SHARD_ARRAY="["
            for i in "${!SHARD_VALUES[@]}"; do
              packages="${SHARD_VALUES[$i]}"

              if [ $i -gt 0 ]; then
                SHARD_ARRAY="${SHARD_ARRAY},"
              fi
              SHARD_ARRAY="${SHARD_ARRAY}\"${packages}\""

              echo "Shard $i: $packages"
            done
            SHARD_ARRAY="${SHARD_ARRAY}]"

            echo "Shard Array: $SHARD_ARRAY"
            echo "Modified Packages: $MODIFIED_PACKAGES"
            echo "===================="

            envman add --key SHARD_ARRAY --value "$SHARD_ARRAY"

    # Share pipeline variables using newline-separated format
    - share-pipeline-variable@1:
        title: Share pipeline variables
        inputs:
        - variables: |-
            SHARD_COUNT
            SHARD_ARRAY
            MODIFIED_PACKAGES

  # Dynamic shard worker - runs N times in parallel (where N = dynamically calculated SHARD_COUNT)
  # Each parallel instance automatically gets $BITRISE_IO_PARALLEL_INDEX (0, 1, 2, ..., N-1)
  # N is determined by: if packages <= threshold, N=1; else N=ceil(package_count / packages_per_shard)
  test_shard:
    description: Run tests for assigned shard packages
    steps:
    - git-clone@8: {}

    - flutter-installer@1:
        inputs:
        - version: $FLUTTER_VERSION

    - script@1:
        title: Install Melos
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            flutter pub global activate melos
            export PATH="$PATH:$HOME/.pub-cache/bin"

    - script@1:
        title: Bootstrap packages
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            export PATH="$PATH:$HOME/.pub-cache/bin"
            melos bootstrap

    - script@1:
        title: Extract packages for this shard from array
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            echo "========================================="
            echo "Shard Index: $BITRISE_IO_PARALLEL_INDEX"
            echo "Shard Count: $SHARD_COUNT"
            echo "Shard Array: $SHARD_ARRAY"
            echo "========================================="

            # Parse JSON array and extract packages for this shard index
            # SHARD_ARRAY is like: ["feature_a,feature_b", "feature_c,feature_d"]
            # We want to get the element at index $BITRISE_IO_PARALLEL_INDEX

            # Use jq to parse JSON array (jq is pre-installed on Bitrise stacks)
            PACKAGES=$(echo "$SHARD_ARRAY" | jq -r ".[$BITRISE_IO_PARALLEL_INDEX]")

            if [ -z "$PACKAGES" ] || [ "$PACKAGES" = "null" ]; then
              echo "ERROR: No packages found for shard $BITRISE_IO_PARALLEL_INDEX"
              exit 1
            fi

            echo "Packages for shard $BITRISE_IO_PARALLEL_INDEX: $PACKAGES"
            envman add --key SHARD_PACKAGES --value "$PACKAGES"

    - script@1:
        title: Install test report tool
        inputs:
        - content: |-
            #!/bin/bash
            set -ex

            # Install junitreport for converting Flutter JSON to JUnit XML
            flutter pub global activate junitreport

    - script@1:
        title: Run tests for assigned packages
        inputs:
        - content: |-
            #!/bin/bash
            set -ex
            export PATH="$PATH:$HOME/.pub-cache/bin"

            echo "========================================="
            echo "Testing Shard $BITRISE_IO_PARALLEL_INDEX"
            echo "Mode: Dynamic sharding ($SHARD_COUNT shards in parallel)"
            echo "Packages: $SHARD_PACKAGES"
            echo "========================================="

            IFS=',' read -ra PKG_ARRAY <<< "$SHARD_PACKAGES"

            # Create directories for test results
            mkdir -p test-results
            mkdir -p "$BITRISE_TEST_RESULT_DIR"

            FAILED=0

            for package in "${PKG_ARRAY[@]}"; do
              echo ""
              echo "========================================="
              echo "Testing package: $package"
              echo "========================================="

              cd "packages/$package"

              # Create subdirectory for this test run
              TEST_RUN_DIR="$BITRISE_TEST_RESULT_DIR/shard${BITRISE_IO_PARALLEL_INDEX}_${package}"
              mkdir -p "$TEST_RUN_DIR"

              JUNIT_OUTPUT="$TEST_RUN_DIR/junit.xml"

              if flutter test --reporter=expanded --file-reporter="json:test-output.json" 2>&1; then
                echo "✅ $package tests passed"
              else
                echo "❌ $package tests failed"
                FAILED=1
              fi

              # Convert test-output.json to JUnit XML using junitreport
              if [ -f "test-output.json" ]; then
                tojunit --input test-output.json --output "$JUNIT_OUTPUT" || {
                  # Fallback: create basic JUnit XML if conversion fails
                  echo "Warning: junitreport conversion failed, creating basic report"
                  cat << 'XMLEOF' > "$JUNIT_OUTPUT"
            <?xml version="1.0" encoding="UTF-8"?>
            <testsuites name="test">
              <testsuite name="test" tests="1">
                <testcase name="Tests" classname="test">
                </testcase>
              </testsuite>
            </testsuites>
            XMLEOF
                }
                echo "Generated JUnit report: $JUNIT_OUTPUT"
              else
                echo "Warning: No test output found for $package"
              fi

              # Create test-info.json with test name
              echo "{\"test-name\":\"Shard $BITRISE_IO_PARALLEL_INDEX - $package\"}" > "$TEST_RUN_DIR/test-info.json"
              echo "Generated test-info.json for $package"

              cd ../..
            done

            echo ""
            echo "========================================="
            echo "Test Results Summary"
            echo "========================================="
            echo "Shard: $BITRISE_IO_PARALLEL_INDEX"
            echo "Packages tested: ${#PKG_ARRAY[@]}"
            echo "JUnit reports generated in: $BITRISE_TEST_RESULT_DIR"
            ls -la "$BITRISE_TEST_RESULT_DIR" || echo "No reports generated"
            echo "========================================="

            if [ $FAILED -eq 1 ]; then
              echo ""
              echo "❌ Shard $BITRISE_IO_PARALLEL_INDEX: Some tests failed!"
              exit 1
            fi

            echo ""
            echo "✅ Shard $BITRISE_IO_PARALLEL_INDEX: All tests passed!"
    - deploy-to-bitrise-io@2:
        title: Deploy test results
        inputs:
        - deploy_path: test-results/
        - is_compress: 'true'
        - is_enable_public_page: 'false'

# Graph-based Pipeline with Dynamic Parallelism
pipelines:
  flutter_test_pipeline:
    workflows:
      # Step 1: Analyze packages and calculate dynamic shard count
      shard_coordinator:
        depends_on: []

      # Step 2: Run tests in parallel across dynamically calculated shards
      # SHARD_COUNT is calculated based on package count and threshold
      # If packages <= threshold, runs in single shard; else ceil(packages / packages_per_shard)
      test_shard:
        depends_on:
        - shard_coordinator
        parallel: $SHARD_COUNT  # Dynamic parallelism based on package count


# Default meta configuration
meta:
  bitrise.io:
    stack: linux-docker-android-22.04
    machine_type_id: standard
